// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoursePurchasePostgreSQL.Models;

public partial class BatchDetail
{
    [Key]
    public int BatchDetailId { get; set; }

    public int? BatchId { get; set; }

    public DateOnly? Date { get; set; }

    public double? HoursTaken { get; set; }

    public string TopicsTaken { get; set; }

    public string Remarks { get; set; }

    [ForeignKey("BatchId")]
    [InverseProperty("BatchDetails")]
    public virtual Batch Batch { get; set; }
}