// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoursePurchasePostgreSQL.Models;

public partial class Batch
{
    [Key]
    public int BatchId { get; set; }

    [StringLength(40)]
    public string BatchName { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? TentativeEndDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public double? Fees { get; set; }

    public double? FeesPaid { get; set; }

    public double? Duration { get; set; }

    public double? HoursTaken { get; set; }

    [StringLength(200)]
    public string Status { get; set; }

    public string Details { get; set; }

    public string Remarks { get; set; }

    [StringLength(300)]
    public string BatchImageUrl { get; set; }

    [InverseProperty("Batch")]
    public virtual ICollection<BatchDetail> BatchDetails { get; set; } = new List<BatchDetail>();

    [InverseProperty("Batch")]
    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();
}