// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoursePurchasePostgreSQL.Models;

[Table("Cart")]
public partial class Cart
{
    [Key]
    public int CartId { get; set; }

    public int? UserID { get; set; }

    public int? Quantity { get; set; }

    [Precision(10, 2)]
    public decimal? Amount { get; set; }

    [Precision(10, 2)]
    public decimal? TotalPrice { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime? CreatedDate { get; set; }

    public int? BatchId { get; set; }

    [ForeignKey("BatchId")]
    [InverseProperty("Carts")]
    public virtual Batch Batch { get; set; }
}