// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoursePurchasePostgreSQL.Models;

[Table("Order")]
public partial class Order
{
    [Key]
    public int OrderId { get; set; }

    public int? BillId { get; set; }

    public int? BatchId { get; set; }

    public int? UserId { get; set; }

    public int? Quantity { get; set; }

    [Precision(10, 0)]
    public decimal? TotalAmount { get; set; }

    public int? OrderStatus { get; set; }

    [Column(TypeName = "timestamp without time zone")]
    public DateTime? Createddate { get; set; }
}